# Generated by Django 4.2.3 on 2023-07-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='lol',
        ),
    ]
