# Generated by Django 4.2.3 on 2023-07-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0004_alter_category_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="modified_time",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified time"),
        ),
    ]
