

version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: arshia
      POSTGRES_PASSWORD: a123
      POSTGRES_DB: recipe2
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  python:
    build: .
    image: python
    container_name: my_django_app
    restart: always
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: recipe2
      POSTGRES_USER: arshia
      POSTGRES_PASSWORD: a123


volumes:
  postgres_data:
